"""empty message

Revision ID: 6af70b79da1c
Revises: fbb5663f9e36
Create Date: 2019-10-09 16:16:45.103425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af70b79da1c'
down_revision = 'fbb5663f9e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_entry',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_entry')
    # ### end Alembic commands ###
